name: echelon
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  action_slider: ^0.7.0
  animations: ^2.0.11
  built_collection: ^5.1.1
  cached_network_image: ^3.3.1
  chopper: ^7.2.0
  cloud_firestore: ^4.15.9
  eva_icons_flutter: ^3.1.0
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_rating_stars: ^1.0.3+4
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  liquid_pull_to_refresh: ^3.0.1
  path_provider: ^2.1.2
  sizer: ^2.0.15
  stacked: ^3.4.0
  stacked_firebase_auth: ^2.20.0
  stacked_services: ^1.4.0
  stacked_themes: ^0.3.12

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  chopper_generator: ^7.2.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
